### ISSUE TITLE
Programação de Funcionalidade - Reservas

### ISSUE THREAD

**Issue by marioliveirad** [ICEI-PUC-Minas-PMV-ADS/pmv-ads-2024-1-e3-proj-mov-t1-meucondominio#69]
> ### **Template Padrão da Aplicação**

|                                |                                |
|--------------------------------|--------------------------------|
| ![Image 1](https://github.com/ICEI-PUC-Minas-PMV-ADS/pmv-ads-2024-1-e3-proj-mov-t1-Condo/assets/127361540/09ad0ee9-1051-45f6-b13c-70de3d12280d) | ![Image 2](https://github.com/ICEI-PUC-Minas-PMV-ADS/pmv-ads-2024-1-e3-proj-mov-t1-Condo/assets/127361540/75460c7b-7c8c-4a46-a54a-149cb52eb438) |
| ![Image](https://github.com/ICEI-PUC-Minas-PMV-ADS/pmv-ads-2024-1-e3-proj-mov-t1-Condo/assets/127361540/a33ef3c5-c8d6-4b16-8b7d-b07cf85339ed) | ![Image](https://github.com/ICEI-PUC-Minas-PMV-ADS/pmv-ads-2024-1-e3-proj-mov-t1-Condo/assets/127361540/f697b7c2-bc50-4d4f-9344-a6f24fe49e19)
| ![Image](https://github.com/ICEI-PUC-Minas-PMV-ADS/pmv-ads-2024-1-e3-proj-mov-t1-Condo/assets/127361540/10aca78c-8b94-428c-933f-051c5ab48f51) |  ![Image](https://github.com/ICEI-PUC-Minas-PMV-ADS/pmv-ads-2024-1-e3-proj-mov-t1-Condo/assets/127361540/e667a485-0cdd-4642-8101-e04a4ae942f4)

**Comment by josuewl** [comment]
![Image](https://github.com/ICEI-PUC-Minas-PMV-ADS/pmv-ads-2024-1-e3-proj-mov-t1-Condo/assets/127361540/47094a14-5604-4112-bcb5-4d40e20ad9c3)
